name = "Fortran90Namelists"
uuid = "8fb689aa-71ff-4044-8071-0cffc910b57d"
authors = ["singularitti <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1"
OrderedCollections = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
