name: Register updated version with Julia Registry

on:
  push:
    branches: master
    paths: Project.toml

jobs:
  reg_updated_pkg_ver:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Check if package version updated in last commit
          id: check
          continue-on-error: true
          run: git diff ${{ github.event.before }} $GITHUB_SHA -- Project.toml | grep version
        - name: Create @JuliaRegistrator register() comment
          if: steps.check.outcome != 'failure'
          uses: peter-evans/commit-comment@v3
          with:
            body: "@JuliaRegistrator register()"
